org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=35
org.gradle.parallel=false
org.gradle.workers.max=1
android.enableLint=false
android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
android.jetifier.use.legacy.logic=false
